# GitHub Linguist Configuration for SUB Language
# This file helps GitHub recognize and highlight .sb files

SUB:
  type: programming
  color: "#FF6B35"
  extensions:
    - ".sb"
  tm_scope: source.sub
  ace_mode: text
  language_id: 999999999
  aliases:
    - sublang
    - sub-lang
